### ISSUE TITLE
By stats widget...

### ISSUE THREAD

**Issue by killeand** [matzman666/PyPipboyApp#17]
Did you mean the player stats like: How many people have you killed, how many times have you stolen, etc..., or did you mean exactly what I made? 

Because I just thought about that stuff, and while it doesn't have anything vital to gameplay in it, we might also want to create a widget for it as well. I mean, the data is being sent, so why the heck not right?

**Comment by matzman666** [comment]
Yes, that was what I meant by statistics browser. Your widgets are actually better because they display useful information. I had the statistics browser on my list just for completeness' sake, but it has low priority for me.

**Comment by killeand** [comment]
Sounds good. I'll see if I can get around to it sometime today, along with the workshops.
