### ISSUE TITLE
Slightly tweaked icons?

### ISSUE THREAD

**Issue by akamal** [matzman666/PyPipboyApp#34]
I've been playing with map marker icons a bit to try and improve things when there are a lot of icons overlapping. I think a simple outline makes things a little clearer, but that may just be me:
![image](https://cloud.githubusercontent.com/assets/1450142/12248459/73142e12-b8b1-11e5-97a8-5755d92316eb.png)

Let me know if you think they're an improvement, and i'll push them to the non-free repo.

**Comment by matzman666** [comment]
I also think that they are an improvement. Let's include them.
