### ISSUE TITLE
Crash when switching global map from orginal to 4k

### ISSUE THREAD

**Issue by bgrimm** [matzman666/PyPipboyApp#42]
Latest pull.
In global map widget changing to map 4k threat level results in exception:
Traceback (most recent call last):
  File "D:\Shared\Projects\Python\PyPipBoy\PyPipBoyApp-RUN-my_current\
", line 1475, in _slotMapFileComboTriggered
    self._createCollectablesMarkers(self.collectableDefs, reset=True)
  File "D:\Shared\Projects\Python\PyPipBoy\PyPipBoyApp-RUN-my_current\
", line 1327, in _createCollectablesMarkers
    marker.setSavedSettings()
  File "D:\Shared\Projects\Python\PyPipBoy\PyPipBoyApp-RUN-my_current\
", line 774, in setSavedSettings
    self.widget.characterDataManager.playerDataPath + self.widget.char
ectablesuffix
TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'

**Comment by matzman666** [comment]
I can reproduce this on a freshly started instance that has never been connected to a running game. Should be fixed with commit 4c56b876252ee573592aee1dd4fe0259554b3d5b.

**Comment by bgrimm** [comment]
Fixed. (also widget position/view save with ini file is fixed too)
